# Generated by Django 2.1 on 2018-08-11 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('task', models.CharField(max_length=256)),
                ('backend_data', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('progress', models.IntegerField(null=True)),
                ('target', models.IntegerField(null=True)),
                ('inputs', models.TextField(default='{}')),
                ('outputs', models.TextField(default='{}')),
                ('messages', models.TextField(default='[]')),
                ('created', models.DateTimeField()),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
            ],
        ),
    ]
