# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Django Task API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        celery-version: [4.*, 5.*]
        django-version: [2.2, 3.1, 3.2]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install celery
      run: |
        pip install "celery==${{ celery-version }}"

    - name: Install Django
      run: |
        - pip install "django==${{ django-verrsion }}"

    - name: Install dependencies
      run: |
        poetry env use system
        poetry install

    - name: Run tests
      run: |
        echo "Using celery version " `celery --version`
        pytest
